name = "honor-chess-api"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[d1_databases]]
binding = "DB"
database_name = "honor-chess-db"
database_id = "a96507a7-41e1-4fee-b900-af082045b51c"

[vars]
JWT_SECRET = "honor-chess-secret-key-2024"
